# Generated by Django 6.0.2 on 2026-02-27 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='code',
            field=models.CharField(blank=True, help_text='Short code used in Batch No. e.g. FO, EO, OS, FR, WS', max_length=10),
        ),
        migrations.AddField(
            model_name='coa',
            name='ar_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='AR No. / Reference No.'),
        ),
        migrations.AddField(
            model_name='coa',
            name='botanical_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='coa',
            name='plant_part',
            field=models.CharField(blank=True, help_text='e.g. Leaf, Seed, Fruit', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='testparameter',
            name='specification',
            field=models.CharField(blank=True, help_text='Standard / expected value shown in COA', max_length=300, null=True),
        ),
        migrations.CreateModel(
            name='COACustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=200)),
                ('specification', models.CharField(blank=True, max_length=300, null=True)),
                ('result', models.CharField(blank=True, max_length=300, null=True)),
                ('order', models.IntegerField(default=0)),
                ('coa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='coa.coa')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
