# Generated by Django 6.0.2 on 2026-02-27 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coa', '0002_category_code_coa_ar_no_coa_botanical_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coaresult',
            name='standard_override',
            field=models.CharField(blank=True, help_text="If lab person changed the standard on the form, it's saved here", max_length=300, null=True),
        ),
    ]
