# Generated by Django 6.0.2 on 2026-03-11 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coa', '0003_coaresult_standard_override'),
    ]

    operations = [
        migrations.CreateModel(
            name='COALabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='Invoice No.')),
                ('gross_weight', models.CharField(blank=True, help_text='e.g. 25.5 kg', max_length=50, null=True)),
                ('tare_weight', models.CharField(blank=True, help_text='e.g. 1.2 kg', max_length=50, null=True)),
                ('net_weight', models.CharField(blank=True, help_text='e.g. 24.3 kg', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='label', to='coa.coa')),
            ],
        ),
    ]
