# Generated by Django 6.0.2 on 2026-03-13 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coa', '0004_coalabel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ItemMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_category', models.CharField(blank=True, max_length=100)),
                ('item_name', models.CharField(max_length=300, unique=True)),
                ('botanical_name', models.CharField(blank=True, max_length=500)),
                ('plant_part', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'ordering': ['item_name'],
            },
        ),
        migrations.AddField(
            model_name='coa',
            name='customer_name',
            field=models.CharField(blank=True, help_text='For records only. Not printed on COA.', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='code',
            field=models.CharField(blank=True, help_text='Short code used in Batch No. e.g. FO, EO, OS', max_length=10),
        ),
        migrations.AlterField(
            model_name='coa',
            name='ar_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='AR No.'),
        ),
        migrations.AlterField(
            model_name='coa',
            name='botanical_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='coa',
            name='plant_part',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='coalabel',
            name='gross_weight',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='coalabel',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='coalabel',
            name='net_weight',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='coalabel',
            name='tare_weight',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='coaresult',
            name='standard_override',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='testparameter',
            name='specification',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
