# Generated by Django 6.0.2 on 2026-04-14 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coa', '0005_customer_itemmaster_coa_customer_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OldCOA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(db_index=True, help_text='Original file name — used for searching', max_length=500)),
                ('customer', models.CharField(blank=True, db_index=True, max_length=300)),
                ('product', models.CharField(blank=True, db_index=True, max_length=300)),
                ('batch', models.CharField(blank=True, max_length=100)),
                ('mfg_date', models.CharField(blank=True, max_length=50)),
                ('botanical', models.CharField(blank=True, max_length=500)),
                ('part_used', models.CharField(blank=True, max_length=300)),
                ('fields', models.TextField(help_text='JSON: {parameter_name: standard_value, ...}')),
            ],
            options={
                'verbose_name': 'Old COA (Archive)',
                'verbose_name_plural': 'Old COAs (Archive)',
                'ordering': ['file_name'],
            },
        ),
        migrations.CreateModel(
            name='ProductStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(db_index=True, max_length=300, unique=True)),
                ('standards', models.TextField(help_text='JSON: {field_name: standard_value, ...}')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['product_name'],
            },
        ),
    ]
