# Generated by Django 6.0.2 on 2026-05-15 04:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coa', '0007_coacustomfield_is_heading_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coa',
            name='ar_no',
        ),
        migrations.AddField(
            model_name='coa',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this COA. Not printed on COA.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coas_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
