# Generated by Django 6.0.2 on 2026-05-16 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coa', '0008_remove_coa_ar_no_coa_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='coalabel',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='item_category',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='oldcoa',
            name='batch',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
