# Generated by Django 6.0.2 on 2026-05-25 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coa', '0008_coaresult_reference'),
        ('coa', '0009_alter_category_name_alter_coalabel_invoice_no_and_more'),
    ]

    operations = [
    ]
